### ISSUE TITLE
[bug] panic when the len(footers) is less than the columns

### ISSUE THREAD

**Issue by eryx** [olekukonko/tablewriter#214]
code
``` go
func main() {

	data := [][]string{
		[]string{"A", "The Good", "500"},
		[]string{"B", "The Very very Bad Man", "288"},
		[]string{"C", "The Ugly", "120"},
		[]string{"D", "The Gopher", "800"},
	}

	table := tablewriter.NewWriter(os.Stdout)
	table.SetHeader([]string{"Name", "Sign", "Rating"})

	table.SetFooter([]string{"Name", "Sign"})

	for _, v := range data {
		table.Append(v)
	}
	table.Render() // Send output
}

```

go run output:

``` shell
+------+-----------------------+--------+
| NAME |         SIGN          | RATING |
+------+-----------------------+--------+
| A    | The Good              |    500 |
| B    | The Very very Bad Man |    288 |
| C    | The Ugly              |    120 |
| D    | The Gopher            |    800 |
+------+-----------------------+--------+
| NAME |         SIGN          |panic: runtime error: index out of range [2] with length 2

goroutine 1 [running]:
github.com/olekukonko/tablewriter.(*Table).printFooter(0xc000130000)
	/opt/workspace/pkg/mod/github.com/olekukonko/tablewriter@v0.0.5/table.go:563 +0xa8a
github.com/olekukonko/tablewriter.(*Table).Render(0xc000130000)
	/opt/workspace/pkg/mod/github.com/olekukonko/tablewriter@v0.0.5/table.go:138 +0xeb
main.main()
...
```

**Comment by olekukonko** [comment]
This has been fixed 

```
┌──────┬───────────────────────┬────────┐
│ NAME │         SIGN          │ RATING │
├──────┼───────────────────────┼────────┤
│ A    │ The Good              │ 500    │
│ B    │ The Very very Bad Man │ 288    │
│ C    │ The Ugly              │ 120    │
│ D    │ The Gopher            │ 800    │
├──────┼───────────────────────┼────────┤
│ Name │                  Sign │        │
└──────┴───────────────────────┴────────┘
```

see https://github.com/olekukonko/tablewriter/pull/240
