### ISSUE TITLE
Header in CSV table is broken

### ISSUE THREAD

**Issue by pires** [olekukonko/tablewriter#39]
```
panic: assignment to entry in nil map

goroutine 1 [running]:
panic(0xfb8e0, 0xc420010990)
        /usr/local/Cellar/go/1.7/libexec/src/runtime/panic.go:500 +0x1a1
github.com/olekukonko/tablewriter.(*Table).parseDimension(0xc42008e400, 0x11a10f, 0x4, 0x0, 0xffffffffffffffff, 0x40, 0xf1940, 0xc42000e501)
        /Users/pires/Work/Projects/go/src/github.com/olekukonko/tablewriter/table.go:488 +0x10b
github.com/olekukonko/tablewriter.(*Table).SetHeader(0xc42008e400, 0xc42003bd18, 0x3, 0x3)
        /Users/pires/Work/Projects/go/src/github.com/olekukonko/tablewriter/table.go:121 +0x87
main.main()
```

Example code:

``` go
table, _ := tablewriter.NewCSV(os.Stdout, "intersects.csv", true)
table.SetHeader([]string{"a", "b", "c"})
table.Render()
```

**Comment by olekukonko** [comment]
Thanks for the report ... I would look into this and get back to you.

**Comment by 4k1k0** [comment]
Hello @olekukonko . Is there any update about this?

**Comment by olekukonko** [comment]
That is the reason you don't suppress errors `_`
